config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root 'questions#index'
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true
  validates :name, presence: true
  validates :content, presence: true, length: { minimum: 5}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to @question, status: :see_other
  end

   private

  def answer_params
    params.require(:answer).permit(:name, :content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  if Rails.env.development?
    skip_before_action :verify_authenticity_token
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new 
  end

  def create
    @question = Question.new(question_params)
    if @question.save
       redirect_to @question
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
     @question = Question.find(params[:id])
     if @question.update(question_params)
        redirect_to @question
     else
      render 'edit', status: :unprocessable_entity
     end
  end
  
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :name, :content)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Qanda" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: @question do |form| %>
  <% if @question.errors.any? %>
      <div>
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div> 
  <div>
    <%= form.submit %>
  </div>  
<% end %>

app/views/questions/edit.html.erb
<h1>Edit</h1>
<%= render partial: 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<%= link_to 'new', new_question_path %>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Name</th>
    <th>Content</th>
    <th></th>
  </tr>
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.id %></td>
      <td><%= question.title %></td>
      <td><%= question.name %></td>
      <td><%= question.content %></td>
      <td><%= link_to 'show', question_path(question) %></td>
      <td><%= link_to 'edit', edit_question_path(question) %></td>
      <td><%= link_to 'destroy', question_path(question), data: { turbo_method: 'delete', turbo_confirm: 'Are you sure'} %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1>New questions</h1>
<%= render partial: 'form' %>

app/views/questions/show.html.erb
<h1>Show</h1>
<p>
  Title: <br>
  <%= @question.title %>
</p>
<p>
  Name: <br>
  <%= @question.name %>
</p>
<p>
  Content: <br>
  <%= @question.content %>
</p>

<h2>Answers</h2>
<% @question.answers.each do |answer|%>
  <p>
    Name: <br>
    <%= answer.name %>
  </p>
   <p>
    Content: <br>
    <%= answer.content %>
  </p>
  <p>
    <%= link_to 'Destroy Answer', [answer.question, answer], data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?'} %>
  </p>
<% end %>

<h2>Add an answer</h2>
<%= form_with model: [@question, @question.answers.build] do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Top', questions_path %>